apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-app
  template:
    metadata:
      labels:
        app: static-app
    spec:
      containers:
        - name: static-app
          image: nagarajutl/static-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-app-service
spec:
  type: NodePort
  selector:
    app: static-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008  # Exposes the app on port 30008
